### ISSUE TITLE
does not work with >195ish tabs

### ISSUE THREAD

**Issue by w4hnsinn** [lunu-bounir/search-all-tabs#10]
As the topic says, I found that the addon does not produce any search results if there are more than a certain number of tabs open at the same time, for me this seems to be around the 195 mark (but I haven't been able to pinpoint the number exactly, perhaps it has to do with memory as well, who knows).

I'm using FF 79.0 (x64) portable, I'm going to check whether the same issue exists in a regular (non-portable) installation of the browser.

**Comment by w4hnsinn** [comment]
> I'm using FF 79.0 (x64) portable, I'm going to check whether the same issue exists in a regular (non-portable) installation of the browser.

Had the same issue with a regular installation (FF 80.0 x64). It only started to work once I closed a number of tabs, see here:

too many tabs open, addon does not work:
![1](https://user-images.githubusercontent.com/24232468/91337487-b3454b00-e7d3-11ea-80f9-1869312b4f78.jpg)

once the number is smaller (in this case apparently 216 is small enough), it works:
![2](https://user-images.githubusercontent.com/24232468/91337512-bf310d00-e7d3-11ea-838a-9fa050e465f8.jpg)

**Comment by lunu-bounir** [comment]
Thanks for the report. The issue was with the memory allocation. Should get fixed by the next release.

**Comment by carehart** [comment]
I can confirm it's working fine for me with MS Edge with 275 open tabs.

I know some want to judge those who have so many open tabs. Different strokes for different folks! Some browsers (and their settings can handle that just fine), and a tool like this extension can help us clean things up. Thanks for it, Lunu! :-)
