### ISSUE TITLE
FIX add option to disable "open in sidebar"

### ISSUE THREAD

**Issue by allanlaal** [lunu-bounir/search-all-tabs#19]
on a slow week i have 200..300 tabs open in 50+ windows on 20..30 desktops, so thats why I use Search All Tabs :)

but currently the price is closing 50+  Search All Tabs sidebars each time I restart firefox :(

**Comment by lunu-bounir** [comment]
Have you tried unchecking the menu's "View -> Sidebar -> Search all Tabs" checkbox?
