### ISSUE TITLE
Discarded tabs (including title and url) seem purposely ignored when searching ("Searching among X documents. Y tabs are ignored.")

### ISSUE THREAD

**Issue by gantheaume** [lunu-bounir/search-all-tabs#21]
I use Search All Tabs a lot as I have regularly hundreds of tabs open. For this same reason, I started to use an extension to automatically discard those that I haven't used in a while ( https://addons.mozilla.org/en-US/firefox/addon/total-suspender/ )

The problem is that as soon as a tab is discarded it doesn't appear in the search results any more. I know that the page content is not indexable, but for the title and the url it should work if I understood the FAQ well.

Plus, it seems that this is a feature, as when one opens the extension widget and clicks in the empty search bar, a mention appears "Searching among X documents. Y tabs are ignored."
The "Y tabs ignored" seems to correspond exactly to the number of suspended tabs I currently have.

Is there an obvious setting I'm missing somewhere?

Tested on fresh profiles in Firefox 88.0 and 78.10.0esr on Debian stable, the behaviour seems easy to reproduce with any tab-discarding extension.

I really would need the discarded tabs titles to be indexed, as most of my tabs are discarded at any given time. I Only use the "index page titles" scope most of the time so it would be perfect (and Search All Tabs is the only tab searching extension that always was snappy enough despite my hundreds to thousands of tabs).

**Comment by pirate** [comment]
I'm on 0.5.1 and this seems to be happening again. It's not searching my tabs suspended with The Marvelous Suspender. I tried toggling all the config options related to scope with no luck.

![image](https://github.com/lunu-bounir/search-all-tabs/assets/511499/2e84c90b-e0a5-40b2-aaee-7d9ea75f0aec)
