### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by grahamperrin** [lunu-bounir/search-all-tabs#26]
Please, what changed?

![image](https://user-images.githubusercontent.com/192271/147934588-d1e5145b-950a-4934-9283-eccc6cb444fe.png)

![image](https://user-images.githubusercontent.com/192271/147934323-dc80ba9b-af64-4b86-bb59-d322d771c490.png)

Empty pages include: 

* https://addons.mozilla.org/en-GB/firefox/addon/search-all-tabs/versions/0.2.7.1/updateinfo/
* https://addons.mozilla.org/en-US/firefox/addon/search-all-tabs/versions/0.2.7.1/updateinfo/
* https://addons.mozilla.org/fr/firefox/addon/search-all-tabs/versions/0.2.7.1/updateinfo/

**Comment by lunu-bounir** [comment]
Nothing has been changed since the 0.2.7 release. Mozilla disabled the extension because it uses "new Function" in the official "PDF.js". I had to submit a new version to explain why this function is needed. Anyhow, I updated the log to reflect the release note of 0.2.7.

**Comment by grahamperrin** [comment]
Empty release notes again: <https://addons.mozilla.org/en-GB/firefox/addon/search-all-tabs/versions/>

What's changed?

**Comment by lunu-bounir** [comment]
It is now updated
