### ISSUE TITLE
Can't find Options menu in Firefox

### ISSUE THREAD

**Issue by jigebren** [lunu-bounir/search-all-tabs#27]
I feel stupid but I can't find the Options menu... (as limiting the searching scope to the tab titles would be enough for my use).
A right-click on the browser action button in the toolbar just launch a Firefox generic context menu (Manage extension, Remove extension, etc.), not a specific "Search all Tabs" option menu.
Tested in Firefox 95.0.2 (x64).
Extension version : 0.2.7.1

**Comment by lunu-bounir** [comment]
Have you tried restarting your browser once? Maybe the context menu event is not being triggered after the install.

**Comment by jigebren** [comment]
I feel stupid again... ;) Restarting Firefox worked actually!
Case closed. Thanks for your help.
