### ISSUE TITLE
Feature request: Close tabs from the search results panel

### ISSUE THREAD

**Issue by damhack** [lunu-bounir/search-all-tabs#30]
When you have a lot of tabs open and want to cull a few, it would be really handy if there was a 'Close Tab' option on the search results.

Either via a select checkbox and bulk close action, or individual close actions that keep the results displayed minus the closed tabs so that you can do a mass cull at your leisure.

**Comment by lunu-bounir** [comment]
<img width="724" alt="s" src="https://user-images.githubusercontent.com/40388903/178135451-25ad4bc4-53a6-4c6b-98d9-dbb3e91fba57.png">

There will be a checkbox on the title area to select multiple items with a mouse or keyboard (Shift + Space). Also, you can select all or none in bulk.

For selected results, you can group them or remove them.
