### ISSUE TITLE
Do you have a way for folks to express thanks, monetarily?

### ISSUE THREAD

**Issue by carehart** [lunu-bounir/search-all-tabs#34]
I'm really enjoying this extension since finding it today. Thank you very much for your efforts so far--especially in your supporting so many browsers--and indeed translating it to over 30 languages!  I'm sure it's a LOT of work. 

I was looking for any way to express appreciation monetarily. I didn't see any means in the extension page, the UI, the FAQ, this github repo's readme, or anywhere else. Have you considered it? Especially since I see (from your web site) that you have dozens of extensions, I'd think many users across them all would want to offer such contribution.

Have I missed that, if it exists? Or perhaps an explanation of why you may opt not to, if you've offered that? Of course, we can offer reviews both at the extension store (of the browser we use) or on your site, where I see you offer your own place for reviews. I'm just asking for the sake of those who may be willing to thank you with "straight cash, homey" :-)  

If you do it, please do be sure to link to it from all those places above. Different people may find only any one of them.

**Comment by binkycs** [comment]
https://add0n.com/search-all-tabs.html

It's on the top right of the page

**Comment by carehart** [comment]
Thanks for that. Are you implying that it was there all the while? If so, ok. I could say "my bad". (If you just added it, great.)

But if it's been there all the while, please note how I'd mentioned all those other places I'd looked for any indication of how one might offer financial support (the extension page, the UI, the FAQ, this github repo's readme), and I didn't see any there. Since I'd missed it, perhaps others would. As I concluded above, might you consider somehow highlighting that option in those other places, for those who might not find or notice that in the top right of that page?

If you disagree and think, "it's good enough as it is", then ok and I'll leave things at that. I was only trying to share an objective outsider perspective. (And I'd honestly not used the tool again since that day I found out about it, but I'm glad to be reminded of it.)

**Comment by binkycs** [comment]
Sorry if my comment came off the wrong way or made it seem like I was the author and was being rude, I wasn't trying to imply anything! I was just perusing around and saw your issue and checked the website to see if they had anything.

**Comment by carehart** [comment]
Ah, OK. Thanks. We're **both** just trying to help them. :-)

**Comment by lunu-bounir** [comment]
Thank you, guys. I'll explore improving it.
