### ISSUE TITLE
SIDEBAR does NOT open at all in Firefox?

### ISSUE THREAD

**Issue by yarub123** [lunu-bounir/search-all-tabs#38]
Is anyone able to get the sidebar to open? The regular popup window works. I'm wondering if maybe this is on Firefox? Thanks in advance. 

FF v112.0.2
MacOS Ventura

**Comment by mtalexan** [comment]
Same.

FF v120.0.1
Ubuntu 22.04

**Comment by lunu-bounir** [comment]
I removed the sidebar support for now. It will be back if I have time to fix the issues.
