### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by AlexD97** [lunu-bounir/search-all-tabs#5]
According to #4 it should be possible to open the window with a keyboard shortcut. What is this shortcut?

**Comment by joinghel** [comment]
You can customize your shortcuts here: chrome://extensions/shortcuts

**Comment by AlexD97** [comment]
Thanks for your answer, but I use Firefox and I cannot find the settings there.

**Comment by joinghel** [comment]
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by AlexD97** [comment]
Thanks!
