### ISSUE TITLE
Keyboard shortcut to open the search window

### ISSUE THREAD

**Issue by m1dnight** [lunu-bounir/search-all-tabs#52]
HI, 

First of all, thanks for the great plugin. I'm looking forward to using it. 
One thing I miss though, is the ability to open up the plugin without using a mouse. So a keyboard shortcut to bring the search box to the front. 

Is there a way to make this happen? 

Thanks,

**Comment by lunu-bounir** [comment]
I added two new FAQs (26 for Chrome, 27 for Firefox)

https://webextension.org/listing/search-all-tabs.html?rv
